### ISSUE TITLE
Client's `extra_headers` is not propagated when getting a Project

### ISSUE THREAD

**Issue by w0ut0** [heartexlabs/label-studio-sdk#45]
I am adding extra headers to my label-studio Client in order to pass an extra reverse proxy we are running:

```python
from label_studio_sdk import Client
ls = Client(url=LABEL_STUDIO_URL, api_key=API_TOKEN, extra_headers={"X-MY-CUSTOM-AUTH": "123456790"})
```

The following works fine:
```python
res = ls.make_request("GET", "/api/projects")
# returns projects
```
Using the SDK fails:
```python
res = ls.get_project(10)
# returns 'unauthenticated', because the header `X-MY-CUSTOM-AUTH` is not provided
```

It seems that the Project class is initialized without propagating the `extra_headers`, and thus subsequent calls fail.

**Comment by makseq** [comment]
Thank you very much for your contribution!

**Comment by CallumMcMahon** [comment]
Just commenting that this problem is also present for client.start_project() where the instantiated project object is not passed `extra_headers`
https://github.com/HumanSignal/label-studio-sdk/blob/490d95cde0fb7517cc65457ba3c964580fd692b1/label_studio_sdk/client.py#L234-L239
assigning the headers to the `requests.Session` is a temp solution to avoid this issue
